project:
  type: website
  output-dir: docs

website:
  title: "howarewedoing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: rank.qmd
        text: test

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

